spring:
  profiles:
    default: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  application:
    name: doldol

cookie:
  domain: .wha1eson.co.kr