spring:
  profiles:
    default: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
  application:
    name: doldol

logging:
  level:
    org.hibernate.SQL: info
    doldol_server.doldol: info